import logging
from functools import reduce
from lark import Lark, UnexpectedInput, UnexpectedToken, UnexpectedCharacters


class miniLispInterpreter:
    """
    The miniLispInterpreter class is responsible for reading the grammar file (grammar.lark),
    creating a Lark parser from it, and then interpreting the user's input code
    by constructing an abstract syntax tree (AST). Once the AST is built, it delegates
    the evaluation of this tree to the function `interpret_AST` (defined below).

    Attributes:
        tree (lark.Tree or None): Holds the most recent parse tree generated by the parser.
        parser (lark.Lark): The Lark parser constructed using the grammar definitions in 'grammar.lark'.
    """
    def __init__(self):
        """
        The constructor initializes the parser by reading the grammar file and
        setting the Lark parser with the 'program' start rule. It uses the
        LALR(1) parser algorithm with a contextual lexer to handle tokens correctly.
        """
        self.tree = None
        with open('grammar.lark') as larkfile:
            self.parser = Lark(larkfile, start='program', parser='lalr', lexer='contextual')

    def interpret(self, code):
        """
        Takes in a code string, attempts to parse it into an AST, and if successful,
        passes it on to `interpret_AST` for evaluation. If parsing fails, a SyntaxError
        is raised.

        Args:
            code (str): The mini-lisp code the user wants to interpret.

        Returns:
            The result of interpreting the top-level expressions in the code.
            This might be a list (for multiple expressions) or a single value.

        Raises:
            SyntaxError: If the input code violates the rules of the grammar.
        """
        try:
            self.tree = self.parser.parse(code)
        except (UnexpectedInput, UnexpectedToken, UnexpectedCharacters):
            # Catching potential parse errors and raising a SyntaxError
            raise SyntaxError('Mini-lisp syntax error.')
        else:
            # If parsing succeeds, evaluate the resulting parse tree
            return interpret_AST(self.tree)


class SymbolTable(dict):
    """
    The SymbolTable class extends Python's built-in dictionary and is used to store
    variable bindings (symbol/value pairs) in the mini-lisp environment. It can also
    store built-in functions (e.g., arithmetic operators, print functions). The SymbolTable
    may optionally chain to another 'outer' SymbolTable to allow for nested scopes.

    Attributes:
        outer (SymbolTable or None): Reference to an outer SymbolTable for variable lookups
            that cannot be resolved in the current scope.
    """
    def __init__(self, basic=False, symbol_names=None, symbol_values=None, outer=None):
        """
        Creates a new SymbolTable (scope). Optionally, if 'basic=True', initializes
        the table with some built-in functions (print_num, print_bool, plus, minus, etc.).

        Args:
            basic (bool): If True, populate this table with built-in functions.
            symbol_names (tuple or list): A sequence of symbol names to bind.
            symbol_values (tuple or list): Corresponding values for each symbol name.
            outer (SymbolTable or None): The outer scope table for chained lookups.
        """
        super(SymbolTable, self).__init__()

        if symbol_names is None:
            symbol_names = tuple()
            symbol_values = tuple()
        # Store the provided symbol names and values in the current SymbolTable
        self.update(zip(symbol_names, symbol_values))
        self.outer = outer

        # If this is a 'basic' environment, define built-in functions/operators
        if basic:
            self.update({
                'print_num': self.print_num,
                'print_bool': self.print_bool,
                'plus': self.plus,
                'minus': self.minus,
                'multiply': self.multiply,
                'divide': self.divide,
                'modulus': self.modulus,
                'greater': self.greater,
                'smaller': self.smaller,
                'equal': self.equal,
                'and_op': self.and_op,
                'or_op': self.or_op,
                'not_op': self.not_op
            })

    def print_bool(self, *args):
        """
        Built-in function to print a boolean value ('#t' or '#f').
        It expects exactly one argument of type bool. Prints '#t' for True,
        and '#f' for False, followed by a newline.
        """
        self.type_checker(bool, args)
        print(['#f', '#t'][args[0]], end='\r\n')

    def print_num(self, *args):
        """
        Built-in function to print integer values. It expects one or more
        integer arguments and prints them all on the same line, followed by
        a newline.
        """
        self.type_checker(int, args)
        print(*args, end='\r\n')

    def plus(self, *args):
        """
        Built-in function to sum multiple integers. It expects one or more
        integer arguments and returns their sum.
        """
        logging.debug(args)
        self.type_checker(int, args)
        return sum(args)

    def minus(self, *args):
        """
        Built-in function to subtract the second integer from the first integer.
        It expects exactly two integers and returns the result of (args[0] - args[1]).
        """
        self.type_checker(int, args)
        return args[0] - args[1]

    def multiply(self, *args):
        """
        Built-in function to multiply multiple integers together. It expects
        one or more integer arguments and returns their product.
        """
        self.type_checker(int, args)
        return reduce(lambda x, y: x * y, args)

    def divide(self, *args):
        """
        Built-in function to perform integer division of the first argument
        by the second argument. It expects exactly two integer arguments.
        """
        self.type_checker(int, args)
        return args[0] // args[1]

    def modulus(self, *args):
        """
        Built-in function for modulus operation (args[0] % args[1]).
        Expects exactly two integer arguments.
        """
        self.type_checker(int, args)
        return args[0] % args[1]

    def greater(self, *args):
        """
        Built-in function to compare two integers using '>'.
        Returns True if the first argument is greater than the second, else False.
        """
        self.type_checker(int, args)
        return args[0] > args[1]

    def smaller(self, *args):
        """
        Built-in function to compare two integers using '<'.
        Returns True if the first argument is smaller than the second, else False.
        """
        self.type_checker(int, args)
        return args[0] < args[1]

    def equal(self, *args):
        """
        Built-in function to check equality among multiple integers.
        Returns True if all integers in 'args' are equal, else False.
        """
        self.type_checker(int, args)
        return args.count(args[0]) == len(args)

    def and_op(self, *args):
        """
        Built-in logical 'and' function for booleans. Returns True only if all
        arguments are True.
        """
        self.type_checker(bool, args)
        return all(args)

    def or_op(self, *args):
        """
        Built-in logical 'or' function for booleans. Returns True if at least one
        of the arguments is True.
        """
        self.type_checker(bool, args)
        return any(args)

    def not_op(self, arg):
        """
        Built-in logical 'not' function for booleans. Returns the negation of the
        single argument provided.
        """
        logging.debug('arg: {}'.format(arg))
        self.type_checker(bool, [arg])
        return not arg

    @staticmethod
    def type_checker(dtype, args):
        """
        Helper method for checking that all items in 'args' match the expected type 'dtype'.
        If any argument has the wrong type, a TypeError is raised.

        Args:
            dtype (type): The expected type (e.g., int or bool).
            args (tuple): The values passed to the built-in function.

        Raises:
            TypeError: If any argument is not of the expected type.
        """
        logging.debug('type-checker => args: {}'.format(args))
        for arg in args:
            if type(arg) != dtype:
                raise TypeError('Expect {} but got {}'.format(dtype, type(arg)))

    def find(self, name):
        """
        Looks up the symbol 'name' in the current SymbolTable and, if necessary,
        in the outer SymbolTable(s). If the symbol does not exist in any accessible
        scope, a NameError is raised.

        Args:
            name (str): The symbol name to find in the table.

        Returns:
            SymbolTable: The SymbolTable in which the symbol is found.

        Raises:
            NameError: If the symbol is not defined in any available scope.
        """
        if name not in self and self.outer is None:
            raise NameError('{} is not founded'.format(name))
        return self if name in self else self.outer.find(name)


class userFunction:
    """
    operates like a stack. That is also the reason why closure is legal.
    I will never use features like closure in my program.

    The userFunction class encapsulates user-defined functions (lambdas).
    It stores the function's parameter names ('args'), the function body
    ('body'), and the environment in which it was defined ('environment').
    """

    def __init__(self, args, body, environment=None):
        """
        Initializes a new userFunction.

        Args:
            args (list or tuple): The names of the parameters (symbols).
            body (lark.Tree): The parse tree representing the function body
                (includes statements and an expression).
            environment (SymbolTable or None): The environment in which the function
                was defined. Defaults to a new basic SymbolTable if None.
        """
        if environment is None:
            environment = SymbolTable(basic=True)
        self.args = args
        self.body = body
        self.environment = environment

    def __call__(self, *params):
        """
        Makes the userFunction instance callable. When the user-defined function
        is invoked, this method creates a new SymbolTable (scope) that maps
        function parameter names (self.args) to the arguments provided
        (params). It then interprets the function body in this new environment.

        Args:
            params (tuple): The actual arguments passed in a function call.

        Returns:
            The result of interpreting the function body in the extended environment.
        """
        # Create a new SymbolTable that chains back to this function's environment
        table = SymbolTable(symbol_names=self.args, symbol_values=params, outer=self.environment)
        # Evaluate the function body in this environment
        return interpret_AST(self.body, table)


def interpret_AST(node, environment=None):
    """
    Recursively interprets a parse tree (node) in the context of the given environment.
    If the environment is not provided, a new basic environment (SymbolTable) is created.

    Depending on the node's data or type, this function:
      - Converts strings that represent integers into `int`.
      - Converts '#t'/'#f' into boolean True/False.
      - Looks up variable bindings in the environment.
      - Dispatches on different node types (if_exp, def_stmt, fun_exp, etc.)
        to handle the corresponding logic.

    Args:
        node: A parse tree node (lark.Tree) or string or number from Lark's parse result.
        environment (SymbolTable): The SymbolTable storing variable/function bindings.

    Returns:
        The result of evaluating the given parse tree node. Could be an integer,
        a boolean, a function, or any other valid mini-lisp value.

    Raises:
        TypeError: If the 'if_exp' test part doesn't evaluate to a boolean.
        NameError: If a referenced variable/function name is not found.
    """
    if environment is None:
        # If no environment is provided, create a new one with basic built-ins.
        environment = SymbolTable(basic=True)

    try:
        # Try to directly convert the node to an integer.
        # If this fails, the exception leads to further checks (like boolean, etc).
        return int(node)
    except (TypeError, ValueError):
        # If it fails conversion, it might be a special symbol like '#t', '#f', or an expression.
        if node == '#t':
            return True
        if node == '#f':
            return False

        # If it's just a string (like a variable name), look it up in the environment.
        if isinstance(node, str):
            return environment.find(node)[node]

        # If node is not a string, it should be a Lark tree with a 'data' attribute.
        if node.data == 'program':
            # The 'program' rule is a list of statements/expressions (children).
            # Evaluate each child, collecting results in a list.
            result = list()
            for child in node.children:
                res = interpret_AST(child, environment)
                if res is not None:
                    result.append(res)
            return result

        elif node.data == 'if_exp':
            # For an if-expression, evaluate the test expression,
            # then decide whether to evaluate the 'then' or 'else' part.
            (test, then, els) = node.children
            test_res = interpret_AST(test, environment)

            # The test result must be boolean; if not, raise a TypeError.
            if not isinstance(test_res, bool):
                raise TypeError("Expect 'boolean' but got 'number'.")
            # If test_res is True, evaluate 'then'; otherwise evaluate 'else'.
            expr = [els, then][test_res]
            return interpret_AST(expr, environment)

        elif node.data == 'def_stmt':
            """
            Definition statement (define variable expression).
            For example: (define x 10).
            We now prohibit redefining variables. If 'var' is already
            in the current environment, raise an error.
            """
            logging.debug('def_stmt => node.children: {}'.format(node.children))
            (var, expr) = node.children
            # Check if 'var' already exists in the current environment
            if var in environment:
                raise NameError(f"Variable '{var}' is already defined. Redefinition not allowed.")
            # Evaluate the expression and store it in the environment under 'var'.
            environment[var] = interpret_AST(expr, environment)

        elif node.data == 'fun_exp':
            # A function expression: (fun (args...) body)
            logging.debug('fun_exp => node.children: {}'.format(node.children))
            # node.children[0] is the list of parameter names, node.children[1] is the body.
            assert len(node.children) == 2
            args = interpret_AST(node.children[0], environment)
            body = interpret_AST(node.children[1], environment)
            # Return a Function object that captures these args, body, and environment.
            return userFunction(args, body, environment)

        elif node.data == 'fun_ids':
            # The parameter list for the function. For example: (x y z)
            logging.debug('node.children: {}'.format(node.children))
            # Return the list of parameter names directly.
            return node.children

        elif node.data == 'fun_body':
            # A function body can have multiple definition statements followed by the final expression.
            logging.debug('fun_body => node.children: {}'.format(node.children))
            # Evaluate each definition statement in order, and then return the last expression.
            for def_stmt in node.children[:-1]:
                interpret_AST(def_stmt, environment)
            return node.children[-1]

        elif node.data == 'fun_call':
            # A function call: (fun_exp param1 param2 ...)
            logging.debug('fun_call => node.children: {}'.format(node.children))
            # node.children[0] is the function (or function name), the rest are the parameters.
            func = interpret_AST(node.children[0], environment)
            params = tuple(interpret_AST(expr, environment) for expr in node.children[1:])
            return func(*params)

        else:
            # If none of the above, we handle arithmetic or logical operations.
            logging.debug('type(node): {}'.format(type(node)))
            logging.debug('node.data: {}'.format(node.data))
            logging.debug('node.children: {}'.format(node.children))
            # node.data corresponds to the operator name (like 'plus', 'minus', etc.),
            # and node.children are the operands.
            func = interpret_AST(node.data, environment)
            args = tuple(interpret_AST(expr, environment) for expr in node.children)
            logging.debug('func: {}'.format(func))
            logging.debug('args: {}'.format(*args))
            return func(*args)
